#!/bin/sh

mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys

args=$(tr ' ' '\n' < /proc/cmdline)
var() {
    echo "$args" | grep "^$1=" | cut -d= -f2
}
arg() {
    echo "$args" | grep -q "^$1$"
}
rescue() {
    echo "Entering rescue shell."
    setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
}

root=$(var root)
init=$(var init)
[ -z "$init" ] && init="/sbin/init"

fsck -p "$root" || rescue

mount -o ro $(findfs "$root") /mnt/root || rescue

arg rescue && rescue

umount /proc /sys /dev

exec switch_root /mnt/root "$init"
